### ISSUE TITLE
Compatibility problem since PyTorch Update

### ISSUE THREAD

**Issue by Nicholasli1995** [jingxil/Neural-Decision-Forests#2]
Since PyTorch updated, 'volatile' no longer works in the newest version. Running the current code will result in CUDA memory error if 'volatile' was not changed into 'with torch.no_grad():'.

**Comment by jingxil** [comment]
Yes, this code is written in PyTorch 0.3. Using the old version of PyTorch should solve the problem. Sorry for this inconvenience.

**Comment by jingxil** [comment]
Now it works with PyTorch 1.0 and above.
