### ISSUE TITLE
Non-linearity in the routing function mentioned in readme file

### ISSUE THREAD

**Issue by katuwalrakesh** [jingxil/Neural-Decision-Forests#3]
The routing function is a running product of decisions where each decision is a value obtained by employing non-linearity (sigmoid) over f. As you have you mentioned in the readme file, "By adding the nonlinearity in the routing function, the accuraries can reach 0.6502 and 0.9753 respectively on the UCI_Yeast and UCI_Letter." The routing function is already a product of values obtained after non-linear operation. So, how and where to again implement this non-linearity?

**Comment by jingxil** [comment]
Hi, katuwalrakesh. I think what I meant is to add non-linearity right after the feature layer. But I can not remember exactly.
