### ISSUE TITLE
Error encountered when testing on adult dataset

### ISSUE THREAD

**Issue by YinghaoHuang91** [jingxil/Neural-Decision-Forests#6]
Hi Jingxil, thanks for making this great repository public for everyone! I really appreciate your work here. And I firstly tried MNIST classification using the default setting, everything is perfect. Issues came when I tried UCI_Adult classification, like shown below:
``
WARNING: RUN WITHOUT GPU 
Use adult dataset
Epoch 1 : Two Stage Learing - Update PI
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    main()
  File "train.py", line 213, in main
    train(model, optim, db, opt)
  File "train.py", line 124, in train
    target_batches.append(cls_onehot[target])
IndexError: tensors used as indices must be long, byte or bool tensors
``

The command I used is: 
``
python train.py -dataset adult -n_class 14  -n_tree 80 -tree_depth 10 -batch_size 1000 -epochs 100
``
Please note that the _n_class_ parameter is adjusted accordingly already.

Do you have any idea where I did things not correctly? Thanks!

**Comment by BillelMidouni** [comment]
Hi, 
I have the same problem. 
do you have an idea for fix the problem ? ;) Thanks !
