### ISSUE TITLE
How to add non-linearity and set parameters to get good results？

### ISSUE THREAD

**Issue by CupidJay** [jingxil/Neural-Decision-Forests#7]
As mentioned in the README file, 'By adding the nonlinearity in the routing function, the accuraries can reach 0.6502 and 0.9753 respectively on the UCI_Yeast and UCI_Letter'.

Actually, I have tried many settings but the accuracies are not that high. So could you tell me how to add non-linearity to get good results (e.g. yeast and letter)? Thank you very much!

**Comment by jingxil** [comment]
Hi, for what I still remember, a DNN (basically several Linear + ReLU layers) will do.
